// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScheduleTaskService.proto

package com.aylaasia.referenceapp.grpc;

public final class ScheduleTaskServiceOuterClass {
  private ScheduleTaskServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface JobOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Job)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     **
     *任务id
     * </pre>
     *
     * <code>string taskId = 1;</code>
     * @return The taskId.
     */
    java.lang.String getTaskId();
    /**
     * <pre>
     **
     *任务id
     * </pre>
     *
     * <code>string taskId = 1;</code>
     * @return The bytes for taskId.
     */
    com.google.protobuf.ByteString
        getTaskIdBytes();

    /**
     * <pre>
     **
     *任务关联主体id，deviceId，groupId...
     * </pre>
     *
     * <code>string taskRelatedId = 2;</code>
     * @return The taskRelatedId.
     */
    java.lang.String getTaskRelatedId();
    /**
     * <pre>
     **
     *任务关联主体id，deviceId，groupId...
     * </pre>
     *
     * <code>string taskRelatedId = 2;</code>
     * @return The bytes for taskRelatedId.
     */
    com.google.protobuf.ByteString
        getTaskRelatedIdBytes();

    /**
     * <pre>
     **
     *倒计时开始计时时间
     * </pre>
     *
     * <code>int64 startTime = 3;</code>
     * @return The startTime.
     */
    long getStartTime();

    /**
     * <pre>
     **
     *cron时间表达式
     * </pre>
     *
     * <code>string cron = 4;</code>
     * @return The cron.
     */
    java.lang.String getCron();
    /**
     * <pre>
     **
     *cron时间表达式
     * </pre>
     *
     * <code>string cron = 4;</code>
     * @return The bytes for cron.
     */
    com.google.protobuf.ByteString
        getCronBytes();

    /**
     * <pre>
     **
     *任务名称
     * </pre>
     *
     * <code>string jobDescribe = 5;</code>
     * @return The jobDescribe.
     */
    java.lang.String getJobDescribe();
    /**
     * <pre>
     **
     *任务名称
     * </pre>
     *
     * <code>string jobDescribe = 5;</code>
     * @return The bytes for jobDescribe.
     */
    com.google.protobuf.ByteString
        getJobDescribeBytes();

    /**
     * <pre>
     **
     *属性设置
     * </pre>
     *
     * <code>repeated .DeviceProperty deviceProperties = 6;</code>
     */
    java.util.List<com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty> 
        getDevicePropertiesList();
    /**
     * <pre>
     **
     *属性设置
     * </pre>
     *
     * <code>repeated .DeviceProperty deviceProperties = 6;</code>
     */
    com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty getDeviceProperties(int index);
    /**
     * <pre>
     **
     *属性设置
     * </pre>
     *
     * <code>repeated .DeviceProperty deviceProperties = 6;</code>
     */
    int getDevicePropertiesCount();
    /**
     * <pre>
     **
     *属性设置
     * </pre>
     *
     * <code>repeated .DeviceProperty deviceProperties = 6;</code>
     */
    java.util.List<? extends com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DevicePropertyOrBuilder> 
        getDevicePropertiesOrBuilderList();
    /**
     * <pre>
     **
     *属性设置
     * </pre>
     *
     * <code>repeated .DeviceProperty deviceProperties = 6;</code>
     */
    com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DevicePropertyOrBuilder getDevicePropertiesOrBuilder(
        int index);

    /**
     * <pre>
     **
     *任务类型：【0：setProperty，1：Reset，2：OTA】
     * </pre>
     *
     * <code>int32 taskType = 7;</code>
     * @return The taskType.
     */
    int getTaskType();

    /**
     * <pre>
     **
     *定时类型 【0：定时，1:倒计时】
     * </pre>
     *
     * <code>int32 timingType = 8;</code>
     * @return The timingType.
     */
    int getTimingType();

    /**
     * <pre>
     **
     *调度状态：0-停止，1-运行
     * </pre>
     *
     * <code>int32 triggerStatus = 9;</code>
     * @return The triggerStatus.
     */
    int getTriggerStatus();
  }
  /**
   * <pre>
   **
   *任务
   * </pre>
   *
   * Protobuf type {@code Job}
   */
  public static final class Job extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Job)
      JobOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Job.newBuilder() to construct.
    private Job(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Job() {
      taskId_ = "";
      taskRelatedId_ = "";
      cron_ = "";
      jobDescribe_ = "";
      deviceProperties_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Job();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Job(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              taskId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              taskRelatedId_ = s;
              break;
            }
            case 24: {

              startTime_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              cron_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              jobDescribe_ = s;
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                deviceProperties_ = new java.util.ArrayList<com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty>();
                mutable_bitField0_ |= 0x00000001;
              }
              deviceProperties_.add(
                  input.readMessage(com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty.parser(), extensionRegistry));
              break;
            }
            case 56: {

              taskType_ = input.readInt32();
              break;
            }
            case 64: {

              timingType_ = input.readInt32();
              break;
            }
            case 72: {

              triggerStatus_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          deviceProperties_ = java.util.Collections.unmodifiableList(deviceProperties_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.internal_static_Job_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.internal_static_Job_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job.class, com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job.Builder.class);
    }

    public static final int TASKID_FIELD_NUMBER = 1;
    private volatile java.lang.Object taskId_;
    /**
     * <pre>
     **
     *任务id
     * </pre>
     *
     * <code>string taskId = 1;</code>
     * @return The taskId.
     */
    @java.lang.Override
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     *任务id
     * </pre>
     *
     * <code>string taskId = 1;</code>
     * @return The bytes for taskId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASKRELATEDID_FIELD_NUMBER = 2;
    private volatile java.lang.Object taskRelatedId_;
    /**
     * <pre>
     **
     *任务关联主体id，deviceId，groupId...
     * </pre>
     *
     * <code>string taskRelatedId = 2;</code>
     * @return The taskRelatedId.
     */
    @java.lang.Override
    public java.lang.String getTaskRelatedId() {
      java.lang.Object ref = taskRelatedId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskRelatedId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     *任务关联主体id，deviceId，groupId...
     * </pre>
     *
     * <code>string taskRelatedId = 2;</code>
     * @return The bytes for taskRelatedId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTaskRelatedIdBytes() {
      java.lang.Object ref = taskRelatedId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskRelatedId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARTTIME_FIELD_NUMBER = 3;
    private long startTime_;
    /**
     * <pre>
     **
     *倒计时开始计时时间
     * </pre>
     *
     * <code>int64 startTime = 3;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public long getStartTime() {
      return startTime_;
    }

    public static final int CRON_FIELD_NUMBER = 4;
    private volatile java.lang.Object cron_;
    /**
     * <pre>
     **
     *cron时间表达式
     * </pre>
     *
     * <code>string cron = 4;</code>
     * @return The cron.
     */
    @java.lang.Override
    public java.lang.String getCron() {
      java.lang.Object ref = cron_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cron_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     *cron时间表达式
     * </pre>
     *
     * <code>string cron = 4;</code>
     * @return The bytes for cron.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCronBytes() {
      java.lang.Object ref = cron_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cron_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JOBDESCRIBE_FIELD_NUMBER = 5;
    private volatile java.lang.Object jobDescribe_;
    /**
     * <pre>
     **
     *任务名称
     * </pre>
     *
     * <code>string jobDescribe = 5;</code>
     * @return The jobDescribe.
     */
    @java.lang.Override
    public java.lang.String getJobDescribe() {
      java.lang.Object ref = jobDescribe_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobDescribe_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     *任务名称
     * </pre>
     *
     * <code>string jobDescribe = 5;</code>
     * @return The bytes for jobDescribe.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJobDescribeBytes() {
      java.lang.Object ref = jobDescribe_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobDescribe_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICEPROPERTIES_FIELD_NUMBER = 6;
    private java.util.List<com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty> deviceProperties_;
    /**
     * <pre>
     **
     *属性设置
     * </pre>
     *
     * <code>repeated .DeviceProperty deviceProperties = 6;</code>
     */
    @java.lang.Override
    public java.util.List<com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty> getDevicePropertiesList() {
      return deviceProperties_;
    }
    /**
     * <pre>
     **
     *属性设置
     * </pre>
     *
     * <code>repeated .DeviceProperty deviceProperties = 6;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DevicePropertyOrBuilder> 
        getDevicePropertiesOrBuilderList() {
      return deviceProperties_;
    }
    /**
     * <pre>
     **
     *属性设置
     * </pre>
     *
     * <code>repeated .DeviceProperty deviceProperties = 6;</code>
     */
    @java.lang.Override
    public int getDevicePropertiesCount() {
      return deviceProperties_.size();
    }
    /**
     * <pre>
     **
     *属性设置
     * </pre>
     *
     * <code>repeated .DeviceProperty deviceProperties = 6;</code>
     */
    @java.lang.Override
    public com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty getDeviceProperties(int index) {
      return deviceProperties_.get(index);
    }
    /**
     * <pre>
     **
     *属性设置
     * </pre>
     *
     * <code>repeated .DeviceProperty deviceProperties = 6;</code>
     */
    @java.lang.Override
    public com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DevicePropertyOrBuilder getDevicePropertiesOrBuilder(
        int index) {
      return deviceProperties_.get(index);
    }

    public static final int TASKTYPE_FIELD_NUMBER = 7;
    private int taskType_;
    /**
     * <pre>
     **
     *任务类型：【0：setProperty，1：Reset，2：OTA】
     * </pre>
     *
     * <code>int32 taskType = 7;</code>
     * @return The taskType.
     */
    @java.lang.Override
    public int getTaskType() {
      return taskType_;
    }

    public static final int TIMINGTYPE_FIELD_NUMBER = 8;
    private int timingType_;
    /**
     * <pre>
     **
     *定时类型 【0：定时，1:倒计时】
     * </pre>
     *
     * <code>int32 timingType = 8;</code>
     * @return The timingType.
     */
    @java.lang.Override
    public int getTimingType() {
      return timingType_;
    }

    public static final int TRIGGERSTATUS_FIELD_NUMBER = 9;
    private int triggerStatus_;
    /**
     * <pre>
     **
     *调度状态：0-停止，1-运行
     * </pre>
     *
     * <code>int32 triggerStatus = 9;</code>
     * @return The triggerStatus.
     */
    @java.lang.Override
    public int getTriggerStatus() {
      return triggerStatus_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTaskIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taskId_);
      }
      if (!getTaskRelatedIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, taskRelatedId_);
      }
      if (startTime_ != 0L) {
        output.writeInt64(3, startTime_);
      }
      if (!getCronBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, cron_);
      }
      if (!getJobDescribeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, jobDescribe_);
      }
      for (int i = 0; i < deviceProperties_.size(); i++) {
        output.writeMessage(6, deviceProperties_.get(i));
      }
      if (taskType_ != 0) {
        output.writeInt32(7, taskType_);
      }
      if (timingType_ != 0) {
        output.writeInt32(8, timingType_);
      }
      if (triggerStatus_ != 0) {
        output.writeInt32(9, triggerStatus_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTaskIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taskId_);
      }
      if (!getTaskRelatedIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, taskRelatedId_);
      }
      if (startTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, startTime_);
      }
      if (!getCronBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, cron_);
      }
      if (!getJobDescribeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, jobDescribe_);
      }
      for (int i = 0; i < deviceProperties_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, deviceProperties_.get(i));
      }
      if (taskType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, taskType_);
      }
      if (timingType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, timingType_);
      }
      if (triggerStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, triggerStatus_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job)) {
        return super.equals(obj);
      }
      com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job other = (com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job) obj;

      if (!getTaskId()
          .equals(other.getTaskId())) return false;
      if (!getTaskRelatedId()
          .equals(other.getTaskRelatedId())) return false;
      if (getStartTime()
          != other.getStartTime()) return false;
      if (!getCron()
          .equals(other.getCron())) return false;
      if (!getJobDescribe()
          .equals(other.getJobDescribe())) return false;
      if (!getDevicePropertiesList()
          .equals(other.getDevicePropertiesList())) return false;
      if (getTaskType()
          != other.getTaskType()) return false;
      if (getTimingType()
          != other.getTimingType()) return false;
      if (getTriggerStatus()
          != other.getTriggerStatus()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TASKID_FIELD_NUMBER;
      hash = (53 * hash) + getTaskId().hashCode();
      hash = (37 * hash) + TASKRELATEDID_FIELD_NUMBER;
      hash = (53 * hash) + getTaskRelatedId().hashCode();
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartTime());
      hash = (37 * hash) + CRON_FIELD_NUMBER;
      hash = (53 * hash) + getCron().hashCode();
      hash = (37 * hash) + JOBDESCRIBE_FIELD_NUMBER;
      hash = (53 * hash) + getJobDescribe().hashCode();
      if (getDevicePropertiesCount() > 0) {
        hash = (37 * hash) + DEVICEPROPERTIES_FIELD_NUMBER;
        hash = (53 * hash) + getDevicePropertiesList().hashCode();
      }
      hash = (37 * hash) + TASKTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getTaskType();
      hash = (37 * hash) + TIMINGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getTimingType();
      hash = (37 * hash) + TRIGGERSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getTriggerStatus();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     *任务
     * </pre>
     *
     * Protobuf type {@code Job}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Job)
        com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.JobOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.internal_static_Job_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.internal_static_Job_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job.class, com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job.Builder.class);
      }

      // Construct using com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDevicePropertiesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        taskId_ = "";

        taskRelatedId_ = "";

        startTime_ = 0L;

        cron_ = "";

        jobDescribe_ = "";

        if (devicePropertiesBuilder_ == null) {
          deviceProperties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          devicePropertiesBuilder_.clear();
        }
        taskType_ = 0;

        timingType_ = 0;

        triggerStatus_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.internal_static_Job_descriptor;
      }

      @java.lang.Override
      public com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job getDefaultInstanceForType() {
        return com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job.getDefaultInstance();
      }

      @java.lang.Override
      public com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job build() {
        com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job buildPartial() {
        com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job result = new com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job(this);
        int from_bitField0_ = bitField0_;
        result.taskId_ = taskId_;
        result.taskRelatedId_ = taskRelatedId_;
        result.startTime_ = startTime_;
        result.cron_ = cron_;
        result.jobDescribe_ = jobDescribe_;
        if (devicePropertiesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            deviceProperties_ = java.util.Collections.unmodifiableList(deviceProperties_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.deviceProperties_ = deviceProperties_;
        } else {
          result.deviceProperties_ = devicePropertiesBuilder_.build();
        }
        result.taskType_ = taskType_;
        result.timingType_ = timingType_;
        result.triggerStatus_ = triggerStatus_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job) {
          return mergeFrom((com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job other) {
        if (other == com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job.getDefaultInstance()) return this;
        if (!other.getTaskId().isEmpty()) {
          taskId_ = other.taskId_;
          onChanged();
        }
        if (!other.getTaskRelatedId().isEmpty()) {
          taskRelatedId_ = other.taskRelatedId_;
          onChanged();
        }
        if (other.getStartTime() != 0L) {
          setStartTime(other.getStartTime());
        }
        if (!other.getCron().isEmpty()) {
          cron_ = other.cron_;
          onChanged();
        }
        if (!other.getJobDescribe().isEmpty()) {
          jobDescribe_ = other.jobDescribe_;
          onChanged();
        }
        if (devicePropertiesBuilder_ == null) {
          if (!other.deviceProperties_.isEmpty()) {
            if (deviceProperties_.isEmpty()) {
              deviceProperties_ = other.deviceProperties_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDevicePropertiesIsMutable();
              deviceProperties_.addAll(other.deviceProperties_);
            }
            onChanged();
          }
        } else {
          if (!other.deviceProperties_.isEmpty()) {
            if (devicePropertiesBuilder_.isEmpty()) {
              devicePropertiesBuilder_.dispose();
              devicePropertiesBuilder_ = null;
              deviceProperties_ = other.deviceProperties_;
              bitField0_ = (bitField0_ & ~0x00000001);
              devicePropertiesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDevicePropertiesFieldBuilder() : null;
            } else {
              devicePropertiesBuilder_.addAllMessages(other.deviceProperties_);
            }
          }
        }
        if (other.getTaskType() != 0) {
          setTaskType(other.getTaskType());
        }
        if (other.getTimingType() != 0) {
          setTimingType(other.getTimingType());
        }
        if (other.getTriggerStatus() != 0) {
          setTriggerStatus(other.getTriggerStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object taskId_ = "";
      /**
       * <pre>
       **
       *任务id
       * </pre>
       *
       * <code>string taskId = 1;</code>
       * @return The taskId.
       */
      public java.lang.String getTaskId() {
        java.lang.Object ref = taskId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       *任务id
       * </pre>
       *
       * <code>string taskId = 1;</code>
       * @return The bytes for taskId.
       */
      public com.google.protobuf.ByteString
          getTaskIdBytes() {
        java.lang.Object ref = taskId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       *任务id
       * </pre>
       *
       * <code>string taskId = 1;</code>
       * @param value The taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       *任务id
       * </pre>
       *
       * <code>string taskId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskId() {
        
        taskId_ = getDefaultInstance().getTaskId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       *任务id
       * </pre>
       *
       * <code>string taskId = 1;</code>
       * @param value The bytes for taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object taskRelatedId_ = "";
      /**
       * <pre>
       **
       *任务关联主体id，deviceId，groupId...
       * </pre>
       *
       * <code>string taskRelatedId = 2;</code>
       * @return The taskRelatedId.
       */
      public java.lang.String getTaskRelatedId() {
        java.lang.Object ref = taskRelatedId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskRelatedId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       *任务关联主体id，deviceId，groupId...
       * </pre>
       *
       * <code>string taskRelatedId = 2;</code>
       * @return The bytes for taskRelatedId.
       */
      public com.google.protobuf.ByteString
          getTaskRelatedIdBytes() {
        java.lang.Object ref = taskRelatedId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskRelatedId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       *任务关联主体id，deviceId，groupId...
       * </pre>
       *
       * <code>string taskRelatedId = 2;</code>
       * @param value The taskRelatedId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskRelatedId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskRelatedId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       *任务关联主体id，deviceId，groupId...
       * </pre>
       *
       * <code>string taskRelatedId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskRelatedId() {
        
        taskRelatedId_ = getDefaultInstance().getTaskRelatedId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       *任务关联主体id，deviceId，groupId...
       * </pre>
       *
       * <code>string taskRelatedId = 2;</code>
       * @param value The bytes for taskRelatedId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskRelatedIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskRelatedId_ = value;
        onChanged();
        return this;
      }

      private long startTime_ ;
      /**
       * <pre>
       **
       *倒计时开始计时时间
       * </pre>
       *
       * <code>int64 startTime = 3;</code>
       * @return The startTime.
       */
      @java.lang.Override
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <pre>
       **
       *倒计时开始计时时间
       * </pre>
       *
       * <code>int64 startTime = 3;</code>
       * @param value The startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTime(long value) {
        
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       *倒计时开始计时时间
       * </pre>
       *
       * <code>int64 startTime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartTime() {
        
        startTime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object cron_ = "";
      /**
       * <pre>
       **
       *cron时间表达式
       * </pre>
       *
       * <code>string cron = 4;</code>
       * @return The cron.
       */
      public java.lang.String getCron() {
        java.lang.Object ref = cron_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cron_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       *cron时间表达式
       * </pre>
       *
       * <code>string cron = 4;</code>
       * @return The bytes for cron.
       */
      public com.google.protobuf.ByteString
          getCronBytes() {
        java.lang.Object ref = cron_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cron_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       *cron时间表达式
       * </pre>
       *
       * <code>string cron = 4;</code>
       * @param value The cron to set.
       * @return This builder for chaining.
       */
      public Builder setCron(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cron_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       *cron时间表达式
       * </pre>
       *
       * <code>string cron = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCron() {
        
        cron_ = getDefaultInstance().getCron();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       *cron时间表达式
       * </pre>
       *
       * <code>string cron = 4;</code>
       * @param value The bytes for cron to set.
       * @return This builder for chaining.
       */
      public Builder setCronBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cron_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object jobDescribe_ = "";
      /**
       * <pre>
       **
       *任务名称
       * </pre>
       *
       * <code>string jobDescribe = 5;</code>
       * @return The jobDescribe.
       */
      public java.lang.String getJobDescribe() {
        java.lang.Object ref = jobDescribe_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jobDescribe_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       *任务名称
       * </pre>
       *
       * <code>string jobDescribe = 5;</code>
       * @return The bytes for jobDescribe.
       */
      public com.google.protobuf.ByteString
          getJobDescribeBytes() {
        java.lang.Object ref = jobDescribe_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jobDescribe_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       *任务名称
       * </pre>
       *
       * <code>string jobDescribe = 5;</code>
       * @param value The jobDescribe to set.
       * @return This builder for chaining.
       */
      public Builder setJobDescribe(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jobDescribe_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       *任务名称
       * </pre>
       *
       * <code>string jobDescribe = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearJobDescribe() {
        
        jobDescribe_ = getDefaultInstance().getJobDescribe();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       *任务名称
       * </pre>
       *
       * <code>string jobDescribe = 5;</code>
       * @param value The bytes for jobDescribe to set.
       * @return This builder for chaining.
       */
      public Builder setJobDescribeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jobDescribe_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty> deviceProperties_ =
        java.util.Collections.emptyList();
      private void ensureDevicePropertiesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          deviceProperties_ = new java.util.ArrayList<com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty>(deviceProperties_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty, com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty.Builder, com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DevicePropertyOrBuilder> devicePropertiesBuilder_;

      /**
       * <pre>
       **
       *属性设置
       * </pre>
       *
       * <code>repeated .DeviceProperty deviceProperties = 6;</code>
       */
      public java.util.List<com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty> getDevicePropertiesList() {
        if (devicePropertiesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(deviceProperties_);
        } else {
          return devicePropertiesBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       **
       *属性设置
       * </pre>
       *
       * <code>repeated .DeviceProperty deviceProperties = 6;</code>
       */
      public int getDevicePropertiesCount() {
        if (devicePropertiesBuilder_ == null) {
          return deviceProperties_.size();
        } else {
          return devicePropertiesBuilder_.getCount();
        }
      }
      /**
       * <pre>
       **
       *属性设置
       * </pre>
       *
       * <code>repeated .DeviceProperty deviceProperties = 6;</code>
       */
      public com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty getDeviceProperties(int index) {
        if (devicePropertiesBuilder_ == null) {
          return deviceProperties_.get(index);
        } else {
          return devicePropertiesBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       **
       *属性设置
       * </pre>
       *
       * <code>repeated .DeviceProperty deviceProperties = 6;</code>
       */
      public Builder setDeviceProperties(
          int index, com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty value) {
        if (devicePropertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDevicePropertiesIsMutable();
          deviceProperties_.set(index, value);
          onChanged();
        } else {
          devicePropertiesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       **
       *属性设置
       * </pre>
       *
       * <code>repeated .DeviceProperty deviceProperties = 6;</code>
       */
      public Builder setDeviceProperties(
          int index, com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty.Builder builderForValue) {
        if (devicePropertiesBuilder_ == null) {
          ensureDevicePropertiesIsMutable();
          deviceProperties_.set(index, builderForValue.build());
          onChanged();
        } else {
          devicePropertiesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       **
       *属性设置
       * </pre>
       *
       * <code>repeated .DeviceProperty deviceProperties = 6;</code>
       */
      public Builder addDeviceProperties(com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty value) {
        if (devicePropertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDevicePropertiesIsMutable();
          deviceProperties_.add(value);
          onChanged();
        } else {
          devicePropertiesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       **
       *属性设置
       * </pre>
       *
       * <code>repeated .DeviceProperty deviceProperties = 6;</code>
       */
      public Builder addDeviceProperties(
          int index, com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty value) {
        if (devicePropertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDevicePropertiesIsMutable();
          deviceProperties_.add(index, value);
          onChanged();
        } else {
          devicePropertiesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       **
       *属性设置
       * </pre>
       *
       * <code>repeated .DeviceProperty deviceProperties = 6;</code>
       */
      public Builder addDeviceProperties(
          com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty.Builder builderForValue) {
        if (devicePropertiesBuilder_ == null) {
          ensureDevicePropertiesIsMutable();
          deviceProperties_.add(builderForValue.build());
          onChanged();
        } else {
          devicePropertiesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       **
       *属性设置
       * </pre>
       *
       * <code>repeated .DeviceProperty deviceProperties = 6;</code>
       */
      public Builder addDeviceProperties(
          int index, com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty.Builder builderForValue) {
        if (devicePropertiesBuilder_ == null) {
          ensureDevicePropertiesIsMutable();
          deviceProperties_.add(index, builderForValue.build());
          onChanged();
        } else {
          devicePropertiesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       **
       *属性设置
       * </pre>
       *
       * <code>repeated .DeviceProperty deviceProperties = 6;</code>
       */
      public Builder addAllDeviceProperties(
          java.lang.Iterable<? extends com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty> values) {
        if (devicePropertiesBuilder_ == null) {
          ensureDevicePropertiesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, deviceProperties_);
          onChanged();
        } else {
          devicePropertiesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       **
       *属性设置
       * </pre>
       *
       * <code>repeated .DeviceProperty deviceProperties = 6;</code>
       */
      public Builder clearDeviceProperties() {
        if (devicePropertiesBuilder_ == null) {
          deviceProperties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          devicePropertiesBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       **
       *属性设置
       * </pre>
       *
       * <code>repeated .DeviceProperty deviceProperties = 6;</code>
       */
      public Builder removeDeviceProperties(int index) {
        if (devicePropertiesBuilder_ == null) {
          ensureDevicePropertiesIsMutable();
          deviceProperties_.remove(index);
          onChanged();
        } else {
          devicePropertiesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       **
       *属性设置
       * </pre>
       *
       * <code>repeated .DeviceProperty deviceProperties = 6;</code>
       */
      public com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty.Builder getDevicePropertiesBuilder(
          int index) {
        return getDevicePropertiesFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       **
       *属性设置
       * </pre>
       *
       * <code>repeated .DeviceProperty deviceProperties = 6;</code>
       */
      public com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DevicePropertyOrBuilder getDevicePropertiesOrBuilder(
          int index) {
        if (devicePropertiesBuilder_ == null) {
          return deviceProperties_.get(index);  } else {
          return devicePropertiesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       **
       *属性设置
       * </pre>
       *
       * <code>repeated .DeviceProperty deviceProperties = 6;</code>
       */
      public java.util.List<? extends com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DevicePropertyOrBuilder> 
           getDevicePropertiesOrBuilderList() {
        if (devicePropertiesBuilder_ != null) {
          return devicePropertiesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(deviceProperties_);
        }
      }
      /**
       * <pre>
       **
       *属性设置
       * </pre>
       *
       * <code>repeated .DeviceProperty deviceProperties = 6;</code>
       */
      public com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty.Builder addDevicePropertiesBuilder() {
        return getDevicePropertiesFieldBuilder().addBuilder(
            com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty.getDefaultInstance());
      }
      /**
       * <pre>
       **
       *属性设置
       * </pre>
       *
       * <code>repeated .DeviceProperty deviceProperties = 6;</code>
       */
      public com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty.Builder addDevicePropertiesBuilder(
          int index) {
        return getDevicePropertiesFieldBuilder().addBuilder(
            index, com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty.getDefaultInstance());
      }
      /**
       * <pre>
       **
       *属性设置
       * </pre>
       *
       * <code>repeated .DeviceProperty deviceProperties = 6;</code>
       */
      public java.util.List<com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty.Builder> 
           getDevicePropertiesBuilderList() {
        return getDevicePropertiesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty, com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty.Builder, com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DevicePropertyOrBuilder> 
          getDevicePropertiesFieldBuilder() {
        if (devicePropertiesBuilder_ == null) {
          devicePropertiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty, com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DeviceProperty.Builder, com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.DevicePropertyOrBuilder>(
                  deviceProperties_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          deviceProperties_ = null;
        }
        return devicePropertiesBuilder_;
      }

      private int taskType_ ;
      /**
       * <pre>
       **
       *任务类型：【0：setProperty，1：Reset，2：OTA】
       * </pre>
       *
       * <code>int32 taskType = 7;</code>
       * @return The taskType.
       */
      @java.lang.Override
      public int getTaskType() {
        return taskType_;
      }
      /**
       * <pre>
       **
       *任务类型：【0：setProperty，1：Reset，2：OTA】
       * </pre>
       *
       * <code>int32 taskType = 7;</code>
       * @param value The taskType to set.
       * @return This builder for chaining.
       */
      public Builder setTaskType(int value) {
        
        taskType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       *任务类型：【0：setProperty，1：Reset，2：OTA】
       * </pre>
       *
       * <code>int32 taskType = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskType() {
        
        taskType_ = 0;
        onChanged();
        return this;
      }

      private int timingType_ ;
      /**
       * <pre>
       **
       *定时类型 【0：定时，1:倒计时】
       * </pre>
       *
       * <code>int32 timingType = 8;</code>
       * @return The timingType.
       */
      @java.lang.Override
      public int getTimingType() {
        return timingType_;
      }
      /**
       * <pre>
       **
       *定时类型 【0：定时，1:倒计时】
       * </pre>
       *
       * <code>int32 timingType = 8;</code>
       * @param value The timingType to set.
       * @return This builder for chaining.
       */
      public Builder setTimingType(int value) {
        
        timingType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       *定时类型 【0：定时，1:倒计时】
       * </pre>
       *
       * <code>int32 timingType = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimingType() {
        
        timingType_ = 0;
        onChanged();
        return this;
      }

      private int triggerStatus_ ;
      /**
       * <pre>
       **
       *调度状态：0-停止，1-运行
       * </pre>
       *
       * <code>int32 triggerStatus = 9;</code>
       * @return The triggerStatus.
       */
      @java.lang.Override
      public int getTriggerStatus() {
        return triggerStatus_;
      }
      /**
       * <pre>
       **
       *调度状态：0-停止，1-运行
       * </pre>
       *
       * <code>int32 triggerStatus = 9;</code>
       * @param value The triggerStatus to set.
       * @return This builder for chaining.
       */
      public Builder setTriggerStatus(int value) {
        
        triggerStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       *调度状态：0-停止，1-运行
       * </pre>
       *
       * <code>int32 triggerStatus = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearTriggerStatus() {
        
        triggerStatus_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Job)
    }

    // @@protoc_insertion_point(class_scope:Job)
    private static final com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job();
    }

    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Job>
        PARSER = new com.google.protobuf.AbstractParser<Job>() {
      @java.lang.Override
      public Job parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Job(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Job> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Job> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetJobListRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetJobListResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     **
     *任务列表
     * </pre>
     *
     * <code>repeated .Job jobs = 1;</code>
     */
    java.util.List<com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job> 
        getJobsList();
    /**
     * <pre>
     **
     *任务列表
     * </pre>
     *
     * <code>repeated .Job jobs = 1;</code>
     */
    com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job getJobs(int index);
    /**
     * <pre>
     **
     *任务列表
     * </pre>
     *
     * <code>repeated .Job jobs = 1;</code>
     */
    int getJobsCount();
    /**
     * <pre>
     **
     *任务列表
     * </pre>
     *
     * <code>repeated .Job jobs = 1;</code>
     */
    java.util.List<? extends com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.JobOrBuilder> 
        getJobsOrBuilderList();
    /**
     * <pre>
     **
     *任务列表
     * </pre>
     *
     * <code>repeated .Job jobs = 1;</code>
     */
    com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.JobOrBuilder getJobsOrBuilder(
        int index);
  }
  /**
   * <pre>
   **
   *任务列表入参
   * </pre>
   *
   * Protobuf type {@code GetJobListResp}
   */
  public static final class GetJobListResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetJobListResp)
      GetJobListRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetJobListResp.newBuilder() to construct.
    private GetJobListResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetJobListResp() {
      jobs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetJobListResp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetJobListResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                jobs_ = new java.util.ArrayList<com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job>();
                mutable_bitField0_ |= 0x00000001;
              }
              jobs_.add(
                  input.readMessage(com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          jobs_ = java.util.Collections.unmodifiableList(jobs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.internal_static_GetJobListResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.internal_static_GetJobListResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp.class, com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp.Builder.class);
    }

    public static final int JOBS_FIELD_NUMBER = 1;
    private java.util.List<com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job> jobs_;
    /**
     * <pre>
     **
     *任务列表
     * </pre>
     *
     * <code>repeated .Job jobs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job> getJobsList() {
      return jobs_;
    }
    /**
     * <pre>
     **
     *任务列表
     * </pre>
     *
     * <code>repeated .Job jobs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.JobOrBuilder> 
        getJobsOrBuilderList() {
      return jobs_;
    }
    /**
     * <pre>
     **
     *任务列表
     * </pre>
     *
     * <code>repeated .Job jobs = 1;</code>
     */
    @java.lang.Override
    public int getJobsCount() {
      return jobs_.size();
    }
    /**
     * <pre>
     **
     *任务列表
     * </pre>
     *
     * <code>repeated .Job jobs = 1;</code>
     */
    @java.lang.Override
    public com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job getJobs(int index) {
      return jobs_.get(index);
    }
    /**
     * <pre>
     **
     *任务列表
     * </pre>
     *
     * <code>repeated .Job jobs = 1;</code>
     */
    @java.lang.Override
    public com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.JobOrBuilder getJobsOrBuilder(
        int index) {
      return jobs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < jobs_.size(); i++) {
        output.writeMessage(1, jobs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < jobs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, jobs_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp)) {
        return super.equals(obj);
      }
      com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp other = (com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp) obj;

      if (!getJobsList()
          .equals(other.getJobsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getJobsCount() > 0) {
        hash = (37 * hash) + JOBS_FIELD_NUMBER;
        hash = (53 * hash) + getJobsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     *任务列表入参
     * </pre>
     *
     * Protobuf type {@code GetJobListResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetJobListResp)
        com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.internal_static_GetJobListResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.internal_static_GetJobListResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp.class, com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp.Builder.class);
      }

      // Construct using com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getJobsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (jobsBuilder_ == null) {
          jobs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          jobsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.internal_static_GetJobListResp_descriptor;
      }

      @java.lang.Override
      public com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp getDefaultInstanceForType() {
        return com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp build() {
        com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp buildPartial() {
        com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp result = new com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp(this);
        int from_bitField0_ = bitField0_;
        if (jobsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            jobs_ = java.util.Collections.unmodifiableList(jobs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.jobs_ = jobs_;
        } else {
          result.jobs_ = jobsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp) {
          return mergeFrom((com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp other) {
        if (other == com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp.getDefaultInstance()) return this;
        if (jobsBuilder_ == null) {
          if (!other.jobs_.isEmpty()) {
            if (jobs_.isEmpty()) {
              jobs_ = other.jobs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureJobsIsMutable();
              jobs_.addAll(other.jobs_);
            }
            onChanged();
          }
        } else {
          if (!other.jobs_.isEmpty()) {
            if (jobsBuilder_.isEmpty()) {
              jobsBuilder_.dispose();
              jobsBuilder_ = null;
              jobs_ = other.jobs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              jobsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getJobsFieldBuilder() : null;
            } else {
              jobsBuilder_.addAllMessages(other.jobs_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job> jobs_ =
        java.util.Collections.emptyList();
      private void ensureJobsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          jobs_ = new java.util.ArrayList<com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job>(jobs_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job, com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job.Builder, com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.JobOrBuilder> jobsBuilder_;

      /**
       * <pre>
       **
       *任务列表
       * </pre>
       *
       * <code>repeated .Job jobs = 1;</code>
       */
      public java.util.List<com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job> getJobsList() {
        if (jobsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(jobs_);
        } else {
          return jobsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       **
       *任务列表
       * </pre>
       *
       * <code>repeated .Job jobs = 1;</code>
       */
      public int getJobsCount() {
        if (jobsBuilder_ == null) {
          return jobs_.size();
        } else {
          return jobsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       **
       *任务列表
       * </pre>
       *
       * <code>repeated .Job jobs = 1;</code>
       */
      public com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job getJobs(int index) {
        if (jobsBuilder_ == null) {
          return jobs_.get(index);
        } else {
          return jobsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       **
       *任务列表
       * </pre>
       *
       * <code>repeated .Job jobs = 1;</code>
       */
      public Builder setJobs(
          int index, com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job value) {
        if (jobsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJobsIsMutable();
          jobs_.set(index, value);
          onChanged();
        } else {
          jobsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       **
       *任务列表
       * </pre>
       *
       * <code>repeated .Job jobs = 1;</code>
       */
      public Builder setJobs(
          int index, com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job.Builder builderForValue) {
        if (jobsBuilder_ == null) {
          ensureJobsIsMutable();
          jobs_.set(index, builderForValue.build());
          onChanged();
        } else {
          jobsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       **
       *任务列表
       * </pre>
       *
       * <code>repeated .Job jobs = 1;</code>
       */
      public Builder addJobs(com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job value) {
        if (jobsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJobsIsMutable();
          jobs_.add(value);
          onChanged();
        } else {
          jobsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       **
       *任务列表
       * </pre>
       *
       * <code>repeated .Job jobs = 1;</code>
       */
      public Builder addJobs(
          int index, com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job value) {
        if (jobsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJobsIsMutable();
          jobs_.add(index, value);
          onChanged();
        } else {
          jobsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       **
       *任务列表
       * </pre>
       *
       * <code>repeated .Job jobs = 1;</code>
       */
      public Builder addJobs(
          com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job.Builder builderForValue) {
        if (jobsBuilder_ == null) {
          ensureJobsIsMutable();
          jobs_.add(builderForValue.build());
          onChanged();
        } else {
          jobsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       **
       *任务列表
       * </pre>
       *
       * <code>repeated .Job jobs = 1;</code>
       */
      public Builder addJobs(
          int index, com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job.Builder builderForValue) {
        if (jobsBuilder_ == null) {
          ensureJobsIsMutable();
          jobs_.add(index, builderForValue.build());
          onChanged();
        } else {
          jobsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       **
       *任务列表
       * </pre>
       *
       * <code>repeated .Job jobs = 1;</code>
       */
      public Builder addAllJobs(
          java.lang.Iterable<? extends com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job> values) {
        if (jobsBuilder_ == null) {
          ensureJobsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, jobs_);
          onChanged();
        } else {
          jobsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       **
       *任务列表
       * </pre>
       *
       * <code>repeated .Job jobs = 1;</code>
       */
      public Builder clearJobs() {
        if (jobsBuilder_ == null) {
          jobs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          jobsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       **
       *任务列表
       * </pre>
       *
       * <code>repeated .Job jobs = 1;</code>
       */
      public Builder removeJobs(int index) {
        if (jobsBuilder_ == null) {
          ensureJobsIsMutable();
          jobs_.remove(index);
          onChanged();
        } else {
          jobsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       **
       *任务列表
       * </pre>
       *
       * <code>repeated .Job jobs = 1;</code>
       */
      public com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job.Builder getJobsBuilder(
          int index) {
        return getJobsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       **
       *任务列表
       * </pre>
       *
       * <code>repeated .Job jobs = 1;</code>
       */
      public com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.JobOrBuilder getJobsOrBuilder(
          int index) {
        if (jobsBuilder_ == null) {
          return jobs_.get(index);  } else {
          return jobsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       **
       *任务列表
       * </pre>
       *
       * <code>repeated .Job jobs = 1;</code>
       */
      public java.util.List<? extends com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.JobOrBuilder> 
           getJobsOrBuilderList() {
        if (jobsBuilder_ != null) {
          return jobsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(jobs_);
        }
      }
      /**
       * <pre>
       **
       *任务列表
       * </pre>
       *
       * <code>repeated .Job jobs = 1;</code>
       */
      public com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job.Builder addJobsBuilder() {
        return getJobsFieldBuilder().addBuilder(
            com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job.getDefaultInstance());
      }
      /**
       * <pre>
       **
       *任务列表
       * </pre>
       *
       * <code>repeated .Job jobs = 1;</code>
       */
      public com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job.Builder addJobsBuilder(
          int index) {
        return getJobsFieldBuilder().addBuilder(
            index, com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job.getDefaultInstance());
      }
      /**
       * <pre>
       **
       *任务列表
       * </pre>
       *
       * <code>repeated .Job jobs = 1;</code>
       */
      public java.util.List<com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job.Builder> 
           getJobsBuilderList() {
        return getJobsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job, com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job.Builder, com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.JobOrBuilder> 
          getJobsFieldBuilder() {
        if (jobsBuilder_ == null) {
          jobsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job, com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.Job.Builder, com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.JobOrBuilder>(
                  jobs_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          jobs_ = null;
        }
        return jobsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetJobListResp)
    }

    // @@protoc_insertion_point(class_scope:GetJobListResp)
    private static final com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp();
    }

    public static com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetJobListResp>
        PARSER = new com.google.protobuf.AbstractParser<GetJobListResp>() {
      @java.lang.Override
      public GetJobListResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetJobListResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetJobListResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetJobListResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.aylaasia.referenceapp.grpc.ScheduleTaskServiceOuterClass.GetJobListResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Job_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Job_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetJobListResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetJobListResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031ScheduleTaskService.proto\032\036google/prot" +
      "obuf/wrappers.proto\032\nBase.proto\032\023DeviceS" +
      "ervice.proto\"\312\001\n\003Job\022\016\n\006taskId\030\001 \001(\t\022\025\n\r" +
      "taskRelatedId\030\002 \001(\t\022\021\n\tstartTime\030\003 \001(\003\022\014" +
      "\n\004cron\030\004 \001(\t\022\023\n\013jobDescribe\030\005 \001(\t\022)\n\020dev" +
      "iceProperties\030\006 \003(\0132\017.DeviceProperty\022\020\n\010" +
      "taskType\030\007 \001(\005\022\022\n\ntimingType\030\010 \001(\005\022\025\n\rtr" +
      "iggerStatus\030\t \001(\005\"$\n\016GetJobListResp\022\022\n\004j" +
      "obs\030\001 \003(\0132\004.Job2\352\002\n\023ScheduleTaskService\022" +
      "/\n\tcreateJob\022\004.Job\032\034.google.protobuf.Str" +
      "ingValue\022\032\n\tupdateJob\022\004.Job\032\007.Result\0222\n\t" +
      "removeJob\022\034.google.protobuf.StringValue\032" +
      "\007.Result\0221\n\010startJob\022\034.google.protobuf.S" +
      "tringValue\032\007.Result\0220\n\007stopJob\022\034.google." +
      "protobuf.StringValue\032\007.Result\022;\n\ngetJobL" +
      "ist\022\034.google.protobuf.StringValue\032\017.GetJ" +
      "obListResp\0220\n\ngetJobInfo\022\034.google.protob" +
      "uf.StringValue\032\004.JobB \n\036com.aylaasia.ref" +
      "erenceapp.grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          Base.getDescriptor(),
          com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.getDescriptor(),
        });
    internal_static_Job_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Job_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Job_descriptor,
        new java.lang.String[] { "TaskId", "TaskRelatedId", "StartTime", "Cron", "JobDescribe", "DeviceProperties", "TaskType", "TimingType", "TriggerStatus", });
    internal_static_GetJobListResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetJobListResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetJobListResp_descriptor,
        new java.lang.String[] { "Jobs", });
    com.google.protobuf.WrappersProto.getDescriptor();
    Base.getDescriptor();
    com.aylaasia.referenceapp.grpc.DeviceServiceOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
